### PR TITLE
Beautyfied json

### PR DESCRIPTION
**Pull request by glimow**
https://github.com/src-d/models/pull/20#discussion_r281683030

### CODE REVIEW

**Comment by glimow** [comment]
@vmarkovtsev

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
https://github.com/src-d/modelforge/blob/master/doc/contributing.md#format-of-the-commit-message

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
Not the same as `json.dump(indent=4, sort_keys=True)`

**Comment by glimow** [comment]
https://github.com/src-d/modelforge/pull/96 @vmarkovtsev removed the sort_keys that we introduced in last PR.
I also ensured the JSON in this PR matches the one produced by `modelforge`

**Comment by vmarkovtsev** [comment]
All the json-s everywhere must be `indent=4, sort_keys=True` @glimow

**Comment by vmarkovtsev** [comment]
I think that `sort_keys=True` is still missing.

**Review by vmarkovtsev — CHANGES_REQUESTED** [review]
There should be 2 separate PRs:

- Readable JSON
- Adding the new model

The current one contains both.

**Pull request closed without merging**
